name: 'Polarity Integration Development Checklist'
description: 'Checks a list of requirements for each Polarity Integration Development'
inputs:
  GITHUB_TOKEN:
    description: 'Github token'
    required: true
branding:
  icon: 'triangle'  
  color: 'green'
runs:
  using: 'node12'
  main: 'index.js'
